Develop
jarviscanada/jarvis_data_eng_shawn pull request #8
Opened 2020-05-08 20:03 UTC by bwaj287

finally

2020-05-09 18:25 UTC, bwaj287 commented
for release CR

2020-05-11 18:55 UTC, jarviscanada approved these changes

2020-05-11 18:55 UTC, jarviscanada commented on linux_sql/README.md
> +**host_usage.sh:** The script collects server usage data and then insert the data into the psql database.
fix markdown..missing a newline..make sure you check the rendered markdown from github webpage
![image](https://user-images.githubusercontent.com/58951265/81599734-c227ff00-9396-11ea-83fb-e192dcb0bd1e.png)

2020-05-11 18:55 UTC, jarviscanada commented on linux_sql/README.md
> +I need to implement the program using bash scripts and the PostgreSQL database in order to monitor the system hardware infomation and cpu resource, and also write SQL queries to answer some business
you implemented

2020-05-11 18:55 UTC, jarviscanada commented on linux_sql/scripts/.bashrc
> +export PGPASSWORD = password
remove this. never commit password...you could get fired :(

2020-05-11 18:55 UTC, jarviscanada commented on linux_sql/scripts/average_memusage.sql
> +from (
put all your queries into `sql/queries.sql`

2020-05-11 18:55 UTC, jarviscanada commented on linux_sql/scripts/hardware_info.sql
> +SELECT cpu_number,id AS host_id,total_mem AS "total_mem(x100MB)"
sql/queries.sql

2020-05-11 18:55 UTC, jarviscanada commented on linux_sql/scripts/host_info.sh
> +EOF
exit $?

2020-05-11 18:55 UTC, jarviscanada commented on linux_sql/scripts/host_usage.sh
> +EOF
exit $?

2020-05-11 18:55 UTC, jarviscanada commented on linux_sql/scripts/test.sh
> +
remove

2020-05-11 18:55 UTC, jarviscanada commented on linux_sql/README.md
> +4) using bash command `crontab -e` into crontable setup page and edit the crontable with command `* * * * * bash /home/centos/dev/jarvis_data_eng_shawn/linux_sql/scripts/host_usage.sh "localhost" 543
README is too short..please see sample 

![image](https://user-images.githubusercontent.com/58951265/81600057-03201380-9397-11ea-9376-ed6ccf32a142.png)

2020-05-11 18:56 UTC, jarviscanada requested changes
fix all and request another review please

2020-05-12 02:09 UTC, bwaj287 commented
changed

2020-05-12 02:09 UTC, merged